# Generated by Django 4.2.8 on 2026-03-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('color_dot', models.CharField(choices=[('pink', 'Hồng'), ('blue', 'Xanh lam'), ('green', 'Xanh lá'), ('orange', 'Cam'), ('purple', 'Tím'), ('teal', 'Xanh mòng két')], default='pink', max_length=20, verbose_name='Màu chấm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
