# Generated by Django 5.2.12 on 2026-03-29 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Mã OTP')),
                ('otp_type', models.CharField(choices=[('register', 'Đăng ký'), ('forgot_password', 'Quên mật khẩu')], max_length=20, verbose_name='Loại OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Hết hạn')),
                ('is_used', models.BooleanField(default=False, verbose_name='Đã sử dụng')),
            ],
            options={
                'verbose_name': 'Token OTP',
                'verbose_name_plural': 'Token OTP',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Ẩn bình luận'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='Số lần báo cáo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='verified_by_expert',
            field=models.BooleanField(default=False, verbose_name='Được chuyên gia kiểm duyệt'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Hình ảnh mô tả'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Ẩn bài viết'),
        ),
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'Công khai'), ('anonymous', 'Ẩn danh')], default='public', max_length=20, verbose_name='Chế độ hiển thị'),
        ),
        migrations.AddField(
            model_name='post',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='Số lần báo cáo'),
        ),
        migrations.AddField(
            model_name='post',
            name='verification_reason',
            field=models.CharField(blank=True, choices=[('accurate', 'Bài viết chứa nội dung phù hợp với kiến thức y khoa hiện hành'), ('safe', 'Thông tin trong bài viết an toàn cho mẹ và bé'), ('useful', 'Bài viết cung cấp kiến thức chăm sóc sức khỏe hữu ích'), ('nutrition', 'Thông tin dinh dưỡng đã được kiểm chứng'), ('confirmed', 'Thông tin trong bài viết đã được bác sĩ xác nhận'), ('reference', 'Bài viết có giá trị tham khảo'), ('expert', 'Nội dung phù hợp với khuyến nghị của chuyên gia')], max_length=20, verbose_name='Lý do kiểm duyệt'),
        ),
        migrations.AddField(
            model_name='post',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kiểm duyệt'),
        ),
        migrations.AddField(
            model_name='post',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_posts', to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm duyệt'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'Bình luận mới'), ('verified', 'Bài viết được kiểm duyệt'), ('report_processed', 'Báo cáo được xử lý'), ('system', 'Thông báo hệ thống')], max_length=20, verbose_name='Loại thông báo')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='forum.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='forum.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('false', 'Sai sự thật hoặc lừa gạt'), ('sexual', 'Khiêu dâm'), ('forbidden', 'Nội dung bị cấm'), ('offensive', 'Phản cảm'), ('violence', 'Bạo lực'), ('fake_news', 'Tin tức bị sai lệch'), ('spam', 'Spam'), ('other', 'Khác')], max_length=20, verbose_name='Loại vi phạm')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do chi tiết')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.comment', verbose_name='Bình luận')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.post', verbose_name='Bài viết')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo')),
            ],
            options={
                'verbose_name': 'Báo cáo vi phạm',
                'verbose_name_plural': 'Báo cáo vi phạm',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('user', 'Người dùng'), ('doctor', 'Bác sĩ/Chuyên gia'), ('admin', 'Quản trị viên')], default='user', max_length=20, verbose_name='Loại tài khoản')),
                ('is_verified_doctor', models.BooleanField(default=False, verbose_name='Bác sĩ đã xác minh')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Tiểu sử')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_categories', models.ManyToManyField(blank=True, related_name='interested_users', to='forum.category', verbose_name='Danh mục quan tâm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
    ]
