# Generated by Django 5.2.12 on 2026-03-31 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_otptoken_comment_is_hidden_comment_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('max_posts_per_day', 'Tối đa bài viết/ngày'), ('max_comments_per_day', 'Tối đa bình luận/ngày'), ('report_threshold', 'Ngưỡng báo cáo để ẩn'), ('email_notifications', 'Bật thông báo email'), ('moderation_required', 'Yêu cầu duyệt bài viết'), ('auto_ban_threshold', 'Tự động ban sau X báo cáo'), ('maintenance_mode', 'Chế độ bảo trì'), ('site_announcement', 'Thông báo website')], max_length=50, unique=True, verbose_name='Khóa cài đặt')),
                ('value', models.TextField(verbose_name='Giá trị')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cập nhật bởi')),
            ],
            options={
                'verbose_name': 'Cài đặt hệ thống',
                'verbose_name_plural': 'Cài đặt hệ thống',
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Qu騷rách'), ('misinformation', 'Thông tin sai lệch'), ('explicit_content', 'Nội dung tác động'), ('repeated_violations', 'Vi phạm lặp lại'), ('other', 'Khác')], max_length=30, verbose_name='Lý do ban')),
                ('reason_detail', models.TextField(verbose_name='Chi tiết lý do')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ban đang hoạt động')),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('unban_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hết ban')),
                ('unban_reason', models.TextField(blank=True, verbose_name='Lý do gỡ ban')),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_issued', to=settings.AUTH_USER_MODEL, verbose_name='Ban bởi')),
                ('unban_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unbans_issued', to=settings.AUTH_USER_MODEL, verbose_name='Gỡ ban bởi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban_record', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Ban người dùng',
                'verbose_name_plural': 'Ban người dùng',
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_ban', 'Ban người dùng'), ('user_delete', 'Xóa người dùng'), ('user_role_change', 'Thay đổi vai trò'), ('post_delete', 'Xóa bài viết'), ('post_hide', 'Ẩn bài viết'), ('post_verify', 'Verify bài viết'), ('comment_delete', 'Xóa bình luận'), ('comment_hide', 'Ẩn bình luận'), ('report_process', 'Xử lý báo cáo'), ('notification_create', 'Tạo thông báo hệ thống'), ('settings_change', 'Thay đổi cài đặt'), ('category_manage', 'Quản lý danh mục'), ('other', 'Khác')], max_length=30, verbose_name='Loại hành động')),
                ('action_description', models.TextField(verbose_name='Mô tả hành động')),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Lỗi')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, verbose_name='Thông báo lỗi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Quản trị viên')),
                ('target_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='forum.comment', verbose_name='Bình luận liên quan')),
                ('target_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='forum.post', verbose_name='Bài viết liên quan')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_target_actions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng liên quan')),
            ],
            options={
                'verbose_name': 'Lịch sử hoạt động admin',
                'verbose_name_plural': 'Lịch sử hoạt động admin',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='forum_admin_admin_i_fbd240_idx'), models.Index(fields=['action_type', '-created_at'], name='forum_admin_action__5e5ca2_idx')],
            },
        ),
    ]
