# Generated by Django 5.2.12 on 2026-04-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_systemsettings_userban_adminactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='Hình ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.post', verbose_name='Bài viết')),
            ],
            options={
                'verbose_name': 'Hình ảnh bài viết',
                'verbose_name_plural': 'Hình ảnh bài viết',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
