# Generated by Django 5.2.12 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verification_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú kiểm duyệt'),
        ),
        migrations.AddField(
            model_name='post',
            name='verification_reasons',
            field=models.TextField(blank=True, verbose_name='Danh sách lý do kiểm duyệt'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doctor_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Chức danh chuyên môn'),
        ),
    ]
