# Generated by Django 5.2.12 on 2026-04-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_userprofile_doctor_title_post_verification_reasons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='otptoken',
            options={'verbose_name': 'Mã OTP', 'verbose_name_plural': 'Mã OTP'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interested_categories',
        ),
    ]
