# Generated by Django 5.2.13 on 2026-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_postverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userban',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Quấy rối'), ('misinformation', 'Thông tin sai lệch'), ('explicit_content', 'Nội dung tác động'), ('repeated_violations', 'Vi phạm lặp lại'), ('other', 'Khác')], max_length=30, verbose_name='Lý do ban'),
        ),
    ]
