# Generated by Django 5.2.13 on 2026-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_userban_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='postverification',
            name='custom_reasons',
            field=models.TextField(blank=True, verbose_name='Lý do bổ sung'),
        ),
    ]
